= swagger2markup-cli
Command line interface (CLI) for Swagger2Markup

image:https://travis-ci.org/Swagger2Markup/swagger2markup-cli.svg?branch=master["Build Status", link="https://travis-ci.org/Swagger2Markup/swagger2markup-cli"] image:https://api.bintray.com/packages/swagger2markup/Maven/swagger2markup-cli/images/download.svg[link="https://bintray.com/swagger2markup/Maven/swagger2markup-cli/_latestVersion"]

== Overview

This is a CLI for https://github.com/Swagger2Markup/swagger2markup[Swagger2Markup].
It converts a Swagger JSON or YAML file into several AsciiDoc or GitHub Flavored Markdown documents which can be combined with hand-written documentation. The Swagger source file can be located locally or remotely via HTTP. Swagger2Markup supports the Swagger 1.2 and 2.0 specification.

== Quick usage
You can clone and build the jar, then use this CLI to generate asciidocs.
    
    gradle assemble
    java -jar ./build/libs/swagger2markup-cli-X.X.X.jar convert -i the_swagger_file.json -d /the/path/to/output

Mac users can use https://brew.sh[Homebrew] to install the Swagger2Markup CLI:

    brew install swagger2markup-cli
    swagger2markup convert -i the_swagger_file.json -d /the/path/to/output

That's all! Then you can checkout http://asciidoctor.org/, find your way to to play with asciidocs.

== Reference documentation

The documentation can be found at https://github.com/Swagger2Markup/swagger2markup#reference-documentation[Reference documentation]

== License

Copyright 2015 Robert Winkler

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
